/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/**********************************************************************************************************************
 *
 * 						Example code to demonstrate the application of the Driver
 * 						The code intends to blink the LEDs at PD12 and PD13
 *
 * ********************************************************************************************************************/

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f407xx.h"
#include "stm32f407xx_gpio_driver.h"
#include "stm32f407xx_gpio_driver.c"

// Defining the handle for the GPIO pin

GPIO_Handle_t hgpio_inp;
GPIO_Handle_t hgpio_out12;
GPIO_Handle_t hgpio_out13;
GPIO_Handle_t hgpio_out14;
GPIO_Handle_t hgpio_out15;


int main(void)
{
	// HANDLER SETTINGS FOR INPUT PIN ON PA0
	hgpio_inp.pGPIOx = GPIOA;
	hgpio_inp.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_0;
	hgpio_inp.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_INPUT;
	hgpio_inp.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NOPUPD;
	hgpio_inp.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_MEDIUM;
	hgpio_inp.GPIO_PinConfig.GPIO_PinOPType = GPIO_OUTPUT_PP;
	hgpio_inp.GPIO_PinConfig.GPIO_PinAltFunMode = GPIO_PIN_ALTFUN_0;

	// HANDLER SETTINGS FOR INPUT PIN ON PD12
	hgpio_out12.pGPIOx = GPIOD;
	hgpio_out12.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_12;
	hgpio_out12.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUTPUT;
	hgpio_out12.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NOPUPD;
	hgpio_out12.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_MEDIUM;
	hgpio_out12.GPIO_PinConfig.GPIO_PinOPType = GPIO_OUTPUT_PP;
	hgpio_out12.GPIO_PinConfig.GPIO_PinAltFunMode = GPIO_PIN_ALTFUN_0;

	// HANDLER SETTINGS FOR INPUT PIN ON PD13
	hgpio_out13.pGPIOx = GPIOD;
	hgpio_out13.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_13;
	hgpio_out13.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUTPUT;
	hgpio_out13.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NOPUPD;
	hgpio_out13.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_MEDIUM;
	hgpio_out13.GPIO_PinConfig.GPIO_PinOPType = GPIO_OUTPUT_PP;
	hgpio_out13.GPIO_PinConfig.GPIO_PinAltFunMode = GPIO_PIN_ALTFUN_0;

	// HANDLER SETTINGS FOR INPUT PIN ON PD14
	hgpio_out14.pGPIOx = GPIOD;
	hgpio_out14.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_14;
	hgpio_out14.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUTPUT;
	hgpio_out14.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NOPUPD;
	hgpio_out14.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_MEDIUM;
	hgpio_out14.GPIO_PinConfig.GPIO_PinOPType = GPIO_OUTPUT_PP;
	hgpio_out14.GPIO_PinConfig.GPIO_PinAltFunMode = GPIO_PIN_ALTFUN_0;

	// HANDLER SETTINGS FOR INPUT PIN ON PD15
	hgpio_out15.pGPIOx = GPIOD;
	hgpio_out15.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_15;
	hgpio_out15.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUTPUT;
	hgpio_out15.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NOPUPD;
	hgpio_out15.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_MEDIUM;
	hgpio_out15.GPIO_PinConfig.GPIO_PinOPType = GPIO_OUTPUT_PP;
	hgpio_out15.GPIO_PinConfig.GPIO_PinAltFunMode = GPIO_PIN_ALTFUN_0;

	// PERIPHERAL CLOCKS ENABLING FOR BOTH PORTS
	GPIO_PericlockControl(GPIOA, ENABLE);
	GPIO_PericlockControl(GPIOD, ENABLE);

	// INITIALISING THE HANDLERS FOR THE PINS
	GPIO_Init(&hgpio_inp);
	GPIO_Init(&hgpio_out12);
	GPIO_Init(&hgpio_out13);
	GPIO_Init(&hgpio_out14);
	GPIO_Init(&hgpio_out15);

	while(1)
	{
		if(GPIO_ReadPin(GPIOA, GPIO_PIN_0) == GPIO_PIN_SET)
		{
			GPIO_WritePin(GPIOD, GPIO_PIN_12, GPIO_PIN_SET);
			GPIO_WritePin(GPIOD, GPIO_PIN_13, GPIO_PIN_SET);
			GPIO_WritePin(GPIOD, GPIO_PIN_14, GPIO_PIN_SET);
			GPIO_WritePin(GPIOD, GPIO_PIN_15, GPIO_PIN_SET);
		}

		else
		{
			GPIO_WritePin(GPIOD, GPIO_PIN_12, GPIO_PIN_RESET);
			GPIO_WritePin(GPIOD, GPIO_PIN_13, GPIO_PIN_RESET);
			GPIO_WritePin(GPIOD, GPIO_PIN_14, GPIO_PIN_RESET);
			GPIO_WritePin(GPIOD, GPIO_PIN_15, GPIO_PIN_RESET);
		}

	}


}
